- name: Enable nonlocal IP binding
  blockinfile:
    path: /etc/sysctl.conf
    block: net.ipv4.ip_nonlocal_bind = 1
  register: sysctl

- name: Reload sysctl config
  command: sysctl -p
  when: sysctl.changed == true
